name: NPM & WebP

# 在 Release 发布时 或手动执行
on:
  release:
    types:
      - published
  workflow_dispatch:


jobs:
  publish-npm:
    runs-on: ubuntu-latest
    # Clone 仓库
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      # 安装 Node.js
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
          registry-url: https://registry.npmjs.org/


      # 发布 NPM 包
      - name: Publish Package
        run: |
          git config --global user.email "icolabot@e.yfun.top"
          git config --global user.name "iColaBot"
          npm version patch
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

      # 删除 app1/ 和 app2/ 下的所有文件
      - name: Delete Files
        run: |
          rm -rf app1/*
          rm -rf app2/*
          touch app1/.gitkeep
          touch app2/.gitkeep

      - name: Push
        run: |
          git add -A
          git commit -m "main"
          git push origin main
